# Generated by Django 5.2.2 on 2025-07-05 09:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Composer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name of the composer.', max_length=100)),
                ('bio', models.TextField(help_text='Short biography of the composer.')),
                ('website', models.URLField(blank=True, help_text='Optional website URL.', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the collection.', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Optional description.')),
                ('image', models.ImageField(blank=True, help_text='Optional image for the collection.', null=True, upload_to='images/collections/')),
                ('composer', models.ForeignKey(help_text='The composer (User) who created this collection.', on_delete=django.db.models.deletion.CASCADE, related_name='collections', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(help_text='Secure token string.', max_length=500)),
                ('expiry_date', models.DateTimeField(help_text='When the token expires.')),
                ('used', models.BooleanField(default=False, help_text='Whether the token has been used.')),
                ('user', models.ForeignKey(help_text='User who requested the token.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SheetMusic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the sheet music.', max_length=255)),
                ('genre', models.CharField(help_text='Genre of the composition.', max_length=100)),
                ('description', models.TextField(help_text='Detailed description or program notes.')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in currency units (e.g., 9.99).', max_digits=10)),
                ('image', models.ImageField(blank=True, help_text='Optional cover image or preview of the music.', null=True, upload_to='images/')),
                ('collection', models.ForeignKey(help_text='Optional collection that this piece belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='sheetmusic', to='set_list.collection')),
                ('composer', models.ForeignKey(help_text="User who composed this music. Must belong to 'composer' group.", limit_choices_to={'groups__name': 'composer'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(choices=[(1, '1 Stars'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')], help_text='Rating from 1 (lowest) to 5 (highest).')),
                ('comment', models.TextField(help_text='Written feedback.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Time the review was submitted.')),
                ('verified', models.BooleanField(default=False, help_text='Flag to indicate if the review has been verified.')),
                ('user', models.ForeignKey(help_text='User who wrote the review.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sheet_music', models.ForeignKey(help_text='The sheet music being reviewed.', on_delete=django.db.models.deletion.CASCADE, to='set_list.sheetmusic')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='Date and time of purchase.')),
                ('user', models.ForeignKey(help_text='User who made the purchase.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sheet_music', models.ForeignKey(help_text='The purchased sheet music item.', on_delete=django.db.models.deletion.CASCADE, to='set_list.sheetmusic')),
            ],
        ),
    ]
